language: go
go:
  - 1.8
  - tip


before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y openvpn
  - go get -t -v ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic .

after_success:
- bash <(curl -s https://codecov.io/bash)
